---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.albConfig.ingressName}}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: {{.Values.deployment.user.path}}
          pathType: Prefix
          backend:
            service:
              name: {{.Values.deployment.user.name}}
              port:
                number: {{.Values.deployment.user.port}}
        - path: {{.Values.deployment.branch.path}}
          pathType: Prefix
          backend:
            service:
              name: {{.Values.deployment.branch.name}}
              port:
                number: {{.Values.deployment.branch.port}}
        - path: {{.Values.deployment.underwriter.path}}
          pathType: Prefix
          backend:
            service:
              name: {{.Values.deployment.underwriter.name}}
              port:
                number: {{.Values.deployment.underwriter.port}}