apiVersion: v1
kind: Secret 
metadata:
  name: database-secret
type: Opaque
data:
  DB_HOST: {{.Values.db.host}}
  DB_NAME: {{.Values.db.name}}
  DB_PASSWORD: {{.Values.db.password}}
  DB_PORT: {{.Values.db.port}}
  DB_USERNAME: {{.Values.db.username}}